- hosts: localhost
  gather_facts: 'yes'
  vars_files:
    - vars.yml
  tasks:
    - name:
      pip:
        name: boto3
        state: present
    - name: Creating Security Group for WebServer on AWS
      ec2_group:
        name: '{{ group_name }}'
        description: Security Group for Web Server allowing port for http and ssh
        region: '{{ region }}'
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: launching ec2 instance for webserver
      amazon.aws.ec2:
        key_name: '{{ key_name }}'
        instance_type: '{{ instance_type }}'
        image: '{{ image_ami }}'
        wait: true
        group: '{{ group_name }}'
        count: 1
        vpc_subnet_id: '{{ vpc_subnet_id }}'
        assign_public_ip: 'yes'
        region: us-east-1
        state: present
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        instance_tags:
          Name: webserver
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: '{{ item.public_ip }}'
        groupname: webserver
      loop: '{{ ec2.instances }}'

      
    - name: Wait for SSH to come up
      wait_for:
        host: '{{ item.public_dns_name }}'
        port: 22
        state: started
      loop: '{{ ec2.instances }}'

